Add code to make MFA optional

diff --git a/assumerole b/assumerole
--- a/assumerole
+++ b/assumerole
@@ -62,6 +62,7 @@ GetAccountInfo() {
        ACCOUNT=$(jq    --raw-output ".assume_roles[\"${aws_account}\"][\"aws_account\"]" ${CONF})
           ROLE=$(jq    --raw-output ".assume_roles[\"${aws_account}\"][\"aws_role\"]"    ${CONF})
        MFA_ARN=$(jq    --raw-output ".assume_roles[\"${aws_account}\"][\"aws_mfa_arn\"]" ${CONF})
+    MFA_ENABLED=$(jq --raw-output ".assume_roles[\"${aws_account}\"][\"aws_mfa_enabled\"]" ${CONF})
 ASSUMEROLE_ENV=$(jq -j --raw-output ".assume_roles[\"${aws_account}\"] | select(.environment != null) | .environment[] | \"export \", .name, \"=\", .value, \";\n\"" ${CONF})
         SSHKEY=$(jq    --raw-output ".assume_roles[\"${aws_account}\"] | select(.sshkey != null) | .sshkey" ${CONF})
 }
@@ -73,15 +74,21 @@ CreateCredentials() {
   [[ "${PROFILE}" = "null" ]] && { echo "aws_profile missing for account ${aws_account} in ${CONF}"; exit 1; }
   [[ "${ACCOUNT}" = "null" ]] && { echo "aws_account missing for account ${aws_account} in ${CONF}"; exit 1; }
   [[ "${ROLE}" = "null" ]]    && { echo "aws_role missing for account ${aws_account} in ${CONF}"; exit 1; }
-  [[ "${MFA_ARN}" = "null" ]] && { echo "aws_mfa_arn missing for account ${aws_account} in ${CONF}"; exit 1; }
 
-  ### Get MFA token from commandline or ask for it
-  if [[ -n ${2} ]]
+  if [[ "${MFA_ENABLED}" = "true" ]] 
   then
-    aws_token=${2}
+    [[ "${MFA_ARN}" = "null" ]] && { echo "aws_mfa_arn missing for account ${aws_account} in ${CONF}"; exit 1; }
+
+    ### Get MFA token from commandline or ask for it
+    if [[ -n ${2} ]]
+    then
+      aws_token=${2}
+    else
+      printf "MFA token: "
+      read aws_token
+    fi
   else
-    printf "MFA token: "
-    read aws_token
+    echo "MFA is disabled"
   fi
 
   unset AWS_ACCESS_KEY_ID
@@ -91,12 +98,20 @@ CreateCredentials() {
 
   export AWS_PROFILE=${PROFILE}
 
-  JSON=$(aws sts assume-role \
-           --role-arn arn:aws:iam::${ACCOUNT}:role/${ROLE} \
-           --role-session-name ${ROLE}${$} \
-           --duration-seconds ${AWS_STS_DURATION_SECONDS:-3600} \
-           --serial-number ${MFA_ARN} \
-           --token-code ${aws_token} 2>/dev/null) || { echo "Error assuming role"; exit 1; }
+  if [[ "${MFA_ENABLED}" = "true" ]] 
+  then
+    JSON=$(aws sts assume-role \
+            --role-arn arn:aws:iam::${ACCOUNT}:role/${ROLE} \
+            --role-session-name ${ROLE}${$} \
+            --duration-seconds ${AWS_STS_DURATION_SECONDS:-3600} \
+            --serial-number ${MFA_ARN} \
+            --token-code ${aws_token} 2>/dev/null) || { echo "Error assuming role"; exit 1; }
+  else
+    JSON=$(aws sts assume-role \
+            --role-arn arn:aws:iam::${ACCOUNT}:role/${ROLE} \
+            --role-session-name ${ROLE}${$} \
+            --duration-seconds ${AWS_STS_DURATION_SECONDS:-3600} 2>/dev/null) || { echo "Error assuming role"; exit 1; }
+  fi
 
       AWS_ACCESS_KEY_ID=$(echo ${JSON} | jq --raw-output ".Credentials[\"AccessKeyId\"]")
   AWS_SECRET_ACCESS_KEY=$(echo ${JSON} | jq --raw-output ".Credentials[\"SecretAccessKey\"]")
